name: Azure AZD Deployment

env:
  environment: ${{ vars.AZURE_ENV_NAME }}
  azureCredentials: ${{ secrets.AZURE_CREDENTIALS }}


on:
  # push:
  #   branches:
  #     - 'main'
  workflow_dispatch:

jobs:
  BuildAndDeploy:
    runs-on: ubuntu-latest
    

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login To Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
    

      - name: Install Azure CLI
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show

      - name: Install azd
        uses: Azure/setup-azd@v1.0.0
        with:
          version: latest
   
      # - name: Deploy to Azure
      #   run: |
      #     azd init -t puicchan/thecatsaidno
      #     azd up --environment $environment

      - name: Log in with Azure (Client Credentials)
        if: ${{ env.azureCredentials != '' }}
        run: |
          $info = $Env:azureCredentials | ConvertFrom-Json -AsHashtable;
          Write-Host "::add-mask::$($info.clientSecret)"

          azd auth login `
            --client-id "$($info.clientId)" `
            --client-secret "$($info.clientSecret)" `
            --tenant-id "$($info.tenantId)"
        shell: pwsh
     

      - name: Provision Infrastructure
        run: azd provision --no-prompt
        shell: pwsh
        env:
          AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
          AZURE_LOCATION: ${{ vars.AZURE_LOCATION }}
          AZURE_ENV_NAME: ${{ vars.AZURE_ENV_NAME }}


      - name: Deploy Application
        run: azd deploy --no-prompt
        shell: pwsh
        env:
          AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
          AZURE_LOCATION: ${{ vars.AZURE_LOCATION }}
          AZURE_ENV_NAME: ${{ vars.AZURE_ENV_NAME }}

