name: Azure AZD Deployment

env:
  environment: dev

on:
  push:
    branches:
      - 'main'

jobs:
  BuildAndDeploy:
    runs-on: ubuntu-latest
    

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Azure CLI
        uses: azure/cli@v1

      - name: Install azd
        uses: Azure/setup-azd@v1.0.0

      - name: Login To Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Deploy to Azure
        run: |
          azd init -t puicchan/thecatsaidno
          azd up --environment $environment

