name: Azure AZD Deployment

env:
  environment: dev

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  BuildAndDeploy:
    runs-on: ubuntu-latest
    

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login To Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
    

      - name: Install Azure CLI
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show

      - name: Install azd
        uses: Azure/setup-azd@v1.0.0
        with:
          version: latest
   
      # - name: Deploy to Azure
      #   run: |
      #     azd init -t puicchan/thecatsaidno
      #     azd up --environment $environment

      - name: Provision Infrastructure
        run: azd provision --no-prompt --environment $environment

      - name: Deploy Application
        run: azd deploy --no-prompt
